import { Callout, Cite, Equation, InlineMath, Refs, Tabs, useShellLang } from '@fasl-work/caos-app-shell';

// Shared themed SVG classes (CSS-var tokens only, repaint with the theme, no hardcoded hex) for the figures.
const SVG_STYLE = `
  .cg-msvg .bx { fill: var(--color-surface-2, var(--color-surface)); stroke: var(--color-border); stroke-width: 1.1; }
  .cg-msvg .hi { stroke: var(--color-accent); } .cg-msvg .gd { stroke: var(--color-good); }
  .cg-msvg .t { fill: var(--color-fg); font-size: 11px; font-weight: 700; }
  .cg-msvg .s { fill: var(--color-fg-subtle); font-size: 9px; }
  .cg-msvg .ax { stroke: var(--color-border); stroke-width: 1; }
  .cg-msvg .la { fill: none; stroke: var(--color-accent); stroke-width: 2; }
  .cg-msvg .lb { fill: none; stroke: var(--color-bad); stroke-width: 2; }
  .cg-msvg .lg { fill: none; stroke: var(--color-good); stroke-width: 2; }
  .cg-msvg .lw { stroke: var(--color-warn); stroke-width: 1.2; stroke-dasharray: 3 3; }
  .cg-msvg .fl { fill: none; stroke: var(--color-fg-faint); stroke-width: 1.5; }
  .cg-msvg .fan { fill: var(--color-accent); opacity: 0.16; }
`;

export default function Methodology() {
  const es = useShellLang() === 'es';
  return (
    <article className="page-body prose">
      <style>{SVG_STYLE}</style>
      <h1>{es ? 'Metodología' : 'Methodology'}</h1>
      <p className="lede">{es
        ? 'Del break-even (la línea base equivocada) → la curva ley-tonelaje → los seis cortes de Lane → la optimización de VAN de punto fijo → la extensión estocástica (roadmap) → los modelos aprendidos. Las ecuaciones término a término, lo exacto siempre distinguido de lo ilustrativo, y lo implementado siempre distinguido de lo planificado.'
        : 'From the break-even (the wrong baseline) → the grade-tonnage curve → Lane\'s six cut-offs → the NPV fixed-point optimization → the stochastic extension (roadmap) → the learned models. The equations term by term, the exact always distinguished from the illustrative, and the implemented always distinguished from the planned.'}{' '}<InlineMath tex="\tau=f+F\delta" /></p>

      <Tabs ariaLabel={es ? 'metodología' : 'methodology'} tabs={[
        // ============================================================ BREAK-EVEN
        {
          id: 'breakeven', label: es ? 'Break-even (base)' : 'Break-even (baseline)',
          content: (
            <div className="cg-doc-sec">
              <p>{es ? 'La respuesta ingenua a "¿qué roca es mineral?" es el ' : 'The naïve answer to "which rock is ore?" is the '}<b>break-even</b>{es ? ': procesar un bloque solo si su valor metálico paga su propio costo de proceso. El ' : ': process a block only if its metal value pays its own processing cost. The '}<b>{es ? 'corte marginal' : 'marginal cut-off'}</b>{es ? ' cubre solo proceso + venta (la minería ya es costo hundido una vez comprometida); el ' : ' covers processing + selling only (mining is sunk once committed); the '}<b>break-even</b>{es ? ' de molienda es el mismo corte sobre base por tonelada de mineral. Ambos excluyen el costo de minería hundido: decidido el bloque ya minado, se procesa si paga su proceso + venta (un break-even a nivel de mina, que sí incluiría minería, decide si minar; no es el corte que usa la App).' : ' milling cut-off is that same cut-off on a per-tonne-of-ore basis. Both exclude the sunk mining cost: for an already-mined block, process it if it pays its own processing + selling (a mine-level break-even, which would include mining, decides whether to mine at all; that is not the App\'s cut-off).'}</p>
              <Equation tex="g_{\text{marg}}=\frac{k}{y(p-r)},\qquad g_{\text{be}}=\frac{h}{y(p-r)}" caption={es ? 'corte marginal y break-even de molienda (ambos solo proceso+venta; la minería es costo hundido, excluida); y = recuperación, p = precio, r = costo de refino/venta por unidad, k = proceso por tonelada tratada, h = proceso por tonelada de mineral' : 'marginal cut-off and milling break-even (both processing+selling only; mining is a sunk cost, excluded); y = recovery, p = price, r = refining/selling cost per unit, k = processing per tonne treated, h = processing per tonne of ore'} />
              <p>{es ? 'El break-even es un número estático: ignora que la mina tiene una vida y que la capacidad es escasa. Procesar un bloque marginal hoy ocupa capacidad de molino que podría haber procesado un bloque de mejor ley, un costo de oportunidad que el break-even no ve. Por eso, sobre la vida de la mina, el break-even deja VAN sobre la mesa.' : 'The break-even is a static number: it ignores that the mine has a life and that capacity is scarce. Processing a marginal block today occupies mill capacity that could have processed a higher-grade block, an opportunity cost the break-even cannot see. So over a mine life, the break-even leaves NPV on the table.'}</p>
              <p>{es ? 'La firma de este error: el break-even produce un corte constante igual al de fin de vida, mientras que la política que maximiza el VAN es más alta al principio y decrece. La diferencia es el ' : 'The signature of the error: the break-even produces a constant cut-off equal to the end-of-life one, whereas the NPV-maximising policy is higher early and declines. The difference is the '}<b>{es ? 'uplift de high-grading' : 'high-grading uplift'}</b>{es ? ', que el App cuantifica caso por caso.' : ', which the App quantifies case by case.'}</p>
              <p>{es ? 'Una sutileza que el producto respeta: el corte marginal (solo proceso + venta) y el break-even (con minería) aplican en momentos distintos. El marginal decide qué hacer con material ya minado, procesarlo o mandarlo a botadero/stock, porque su costo de minería ya es hundido; el break-even decide en la planificación qué material vale la pena minar. Usar el marginal donde corresponde el break-even sobreestima las reservas; el producto los mantiene separados.' : 'A subtlety the product respects: the marginal cut-off (processing + selling only) and the break-even (with mining) apply at different moments. The marginal decides what to do with already-mined material, process it or send it to waste/stockpile, because its mining cost is already sunk; the break-even decides at the planning stage which material is worth mining. Using the marginal where the break-even belongs overstates reserves; the product keeps them apart.'}</p>
              <figure className="cg-fig">
                <svg viewBox="0 0 460 220" width="100%" role="img" className="cg-msvg" aria-label={es ? 'VAN vs corte: break-even vs el óptimo de Lane' : 'NPV vs cut-off: break-even vs the Lane optimum'}>
                  <line className="ax" x1="44" y1="180" x2="440" y2="180" /><line className="ax" x1="44" y1="20" x2="44" y2="180" />
                  <path className="la" d="M48,150 C120,60 200,40 250,46 C320,54 400,120 436,168" />
                  <line className="lw" x1="120" y1="20" x2="120" y2="180" /><text className="s" x="86" y="34">break-even</text>
                  <line className="gd" x1="250" y1="20" x2="250" y2="180" style={{ strokeWidth: 1.2, strokeDasharray: '3 3' }} /><text className="s" x="256" y="34">{es ? 'óptimo de Lane' : 'Lane optimum'}</text>
                  <text className="s" x="200" y="200">{es ? 'corte →' : 'cut-off →'}</text><text className="s" x="6" y="100" transform="rotate(-90 14 100)">VAN</text>
                  <text className="s" x="300" y="70">{es ? 'VAN dejado en la mesa' : 'NPV left on the table'}</text>
                </svg>
                <figcaption>{es ? 'El break-even (constante) cae a la izquierda del pico de VAN; Lane elige el corte del pico y lo deja decrecer.' : 'The break-even (constant) sits left of the NPV peak; Lane picks the peak cut-off and lets it decline.'}</figcaption>
              </figure>
              <Callout variant="honest" title={es ? 'Por qué el break-even es la línea base, no la respuesta' : 'Why break-even is the baseline, not the answer'}>
                {es ? 'Casi toda planilla de cálculo usa break-even, y casi siempre está mal sobre una vida de mina. Es el control C-BREAKEVEN del producto: cuando la tasa de descuento δ = 0 (sin valor temporal) y la capacidad no limita, el óptimo de Lane debe colapsar al break-even, eso prueba que el término de costo de oportunidad está correcto.' : 'Almost every spreadsheet uses break-even, and it is almost always wrong over a mine life. It is the product\'s C-BREAKEVEN control: when the discount rate δ = 0 (no time value) and capacity does not bind, the Lane optimum must collapse to the break-even, that proves the opportunity-cost term is correct.'}
              </Callout>
              <Refs ids={['lane1964', 'lane1988']} label="Refs" />
            </div>
          ),
        },
        // ============================================================ GRADE-TONNAGE
        {
          id: 'gt', label: es ? 'Ley-tonelaje' : 'Grade-tonnage',
          content: (
            <div className="cg-doc-sec">
              <p>{es ? 'El depósito entra como una ' : 'The deposit enters as a '}<b>{es ? 'curva ley-tonelaje' : 'grade-tonnage curve'}</b>{es ? ', el tonelaje sobre cada corte y su ley media. Las leyes son clásicamente lognormales (Krige/Sichel), así que el depósito se modela como una distribución lognormal de la ley con media ' : ', the tonnage above each cut-off and its mean grade. Grades are classically lognormal (Krige/Sichel), so the deposit is modelled as a lognormal distribution of grade with mean '}<InlineMath tex="M" />{es ? ' y coeficiente de variación ' : ' and coefficient of variation '}<InlineMath tex="cv" />{es ? '. Para un corte ' : '. For a cut-off '}<InlineMath tex="g_c" />{es ? ' la fracción mineral y la ley media del mineral son analíticas:' : ' the ore fraction and the average ore grade are analytic:'}</p>
              <Equation tex="\phi(g_c)=\Phi\!\left(\tfrac{\mu-\ln g_c}{\sigma}\right),\qquad \bar g(g_c)=M\,\frac{\Phi\!\left(\tfrac{\mu-\ln g_c}{\sigma}+\sigma\right)}{\Phi\!\left(\tfrac{\mu-\ln g_c}{\sigma}\right)}" caption={es ? 'fracción mineral φ (Φ = CDF normal estándar) y ley media del mineral ḡ sobre el corte g_c' : 'ore fraction φ (Φ = standard-normal CDF) and the average ore grade ḡ above the cut-off g_c'} />
              <p>{es ? 'con ' : 'with '}<InlineMath tex="\sigma^2=\ln(1+cv^2)" />{es ? ' y ' : ' and '}<InlineMath tex="\mu=\ln M-\sigma^2/2" />{es ? '. Subir el corte baja la fracción mineral φ (menos tonelaje paga) pero sube la ley media ḡ (lo que queda es más rico), el trade-off central de toda la teoría. Cuando ' : '. Raising the cut-off lowers the ore fraction φ (less tonnage qualifies) but raises the mean grade ḡ (what remains is richer), the central trade-off of the whole theory. As '}<InlineMath tex="cv\to0" />{es ? ' el depósito es de ley única (todo o nada): el control C-UNIFORM.' : ' the deposit is single-grade (all-or-nothing): the C-UNIFORM control.'}</p>
              <Equation tex="T_{\text{ore}}(g_c)=T_0\,\phi(g_c),\qquad \text{metal}(g_c)=T_0\,\phi(g_c)\,\bar g(g_c)\,y" caption={es ? 'tonelaje de mineral y metal recuperable sobre el corte (T₀ = tonelaje total in-situ, y = recuperación)' : 'ore tonnage and recoverable metal above the cut-off (T₀ = total in-situ tonnage, y = recovery)'} />
              <p>{es ? 'La curva ley-tonelaje es la interfaz universal del producto: cualquier depósito, un modelo de bloques real, un deck publicado de un estudio de factibilidad, o el generador sintético, se reduce a esta misma forma (φ y ḡ en función del corte), y el motor de Lane lee exactamente esa forma. Eso desacopla la geología del optimizador: la economía no necesita saber de dónde vino el depósito, solo su curva. El Contrato 1 valida que la curva entregada sea monótona y físicamente plausible antes de pasarla al motor.' : 'The grade-tonnage curve is the product\'s universal interface: any deposit, a real block model, a published feasibility-study deck, or the synthetic generator, reduces to this same shape (φ and ḡ as functions of the cut-off), and the Lane engine reads exactly that shape. This decouples the geology from the optimizer: the economics need not know where the deposit came from, only its curve. Contract 1 validates that the supplied curve is monotone and physically plausible before it reaches the engine.'}</p>
              <p>{es ? 'En la construcción real intervienen la dilución y la recuperación minera: el estéril bajo el corte que igual se extrae con el mineral baja la ley alimentada, y el mineral que no se recupera del banco (pérdida minera) reduce el tonelaje pagable. El producto modela el depósito limpio y expone esos factores como supuestos explícitos en vez de esconderlos en un único número de ley, porque una ley diluida mal aplicada es uno de los errores más caros de la planificación.' : 'The real construction also involves dilution and mining recovery: waste below the cut-off that is mined with the ore lowers the fed grade, and ore not recovered from the bench (mining loss) reduces the payable tonnage. The product models the clean deposit and exposes these factors as explicit assumptions rather than hiding them inside a single grade number, because a mis-applied diluted grade is one of the costliest errors in planning.'}</p>
              <figure className="cg-fig">
                <svg viewBox="0 0 460 200" width="100%" role="img" className="cg-msvg" aria-label={es ? 'curva ley-tonelaje: fracción mineral y ley media vs corte' : 'grade-tonnage curve: ore fraction and mean grade vs cut-off'}>
                  <line className="ax" x1="44" y1="170" x2="440" y2="170" /><line className="ax" x1="44" y1="16" x2="44" y2="170" />
                  <path className="la" d="M48,28 C120,40 220,90 320,140 C370,160 410,166 436,168" /><text className="s" x="60" y="44">φ {es ? '(fracción mineral)' : '(ore fraction)'}</text>
                  <path className="lg" d="M48,150 C140,120 240,86 340,58 C380,46 410,38 436,30" /><text className="s" x="300" y="50">ḡ {es ? '(ley media)' : '(mean grade)'}</text>
                  <text className="s" x="210" y="192">{es ? 'corte g_c →' : 'cut-off g_c →'}</text>
                </svg>
                <figcaption>{es ? 'Subir el corte cambia tonelaje por ley: φ baja, ḡ sube. Lane elige el punto que maximiza el VAN, no el tonelaje.' : 'Raising the cut-off trades tonnage for grade: φ falls, ḡ rises. Lane picks the point that maximises NPV, not tonnage.'}</figcaption>
              </figure>
              <Callout variant="note" title={es ? 'Caveat de soporte (SMU)' : 'Support (SMU) caveat'}>
                {es ? 'La curva ley-tonelaje depende del soporte de la unidad mínima de minería y del efecto de información: una distribución sintética gruesa puede sobreestimar la selectividad. Los depósitos del producto son sintéticos (tipo pórfido), declarados como tales; no se afirma exactitud de mina real a partir de ellos.' : 'The grade-tonnage curve depends on the selective-mining-unit support and the information effect: a coarse synthetic distribution can overstate selectivity. The product\'s deposits are synthetic (porphyry-like), stated as such; no real-mine accuracy is claimed from them.'}
              </Callout>
              <Refs ids={['lane1964', 'lane1988']} label="Refs" />
            </div>
          ),
        },
        // ============================================================ LANE CUT-OFFS
        {
          id: 'lane', label: es ? 'Cortes de Lane' : 'Lane cut-offs',
          content: (
            <div className="cg-doc-sec">
              <p>{es ? 'El margen por unidad de ley por tonelada de mineral es ' : 'The margin per unit grade per tonne of ore is '}<InlineMath tex="y(p-k)" />{es ? '. Lane define seis cortes característicos. Tres son ' : '. Lane defines six characteristic cut-offs. Three are '}<b>{es ? 'limitantes' : 'limiting'}</b>{es ? ': cada uno asume que una etapa (mina, molino o mercado) es el cuello de botella. El término ' : ': each assumes one stage (mine, mill or market) is the bottleneck. The term '}<InlineMath tex="\tau=f+F\delta" />{es ? ' es el costo de oportunidad de un año de la capacidad escasa (' : ' is the opportunity cost of a year of the scarce capacity ('}<InlineMath tex="F" />{es ? ' = el VAN de la operación remanente):' : ' = the NPV of the remaining operation):'}</p>
              <Equation tex="g_{\text{mina}}=\frac{h}{y(p-k)},\quad g_{\text{molino}}=\frac{h+\tau/H}{y(p-k)},\quad g_{\text{mercado}}=\frac{h}{y\big((p-k)-\tau/K\big)}" caption={es ? 'cortes limitantes: mina = break-even (tiempo de molino libre); molino sube por τ/H; mercado sube por τ/K. H = capacidad de molino, K = capacidad de mercado.' : 'limiting cut-offs: mine = break-even (mill time is free); mill is raised by τ/H; market is raised by τ/K. H = mill capacity, K = market capacity.'} />
              <p>{es ? 'Los otros tres son ' : 'The other three are '}<b>{es ? 'balanceadores' : 'balancing'}</b>{es ? ' (mina-molino, molino-mercado, mina-mercado): el corte en que dos etapas se saturan simultáneamente, igualando sus tiempos de procesamiento sobre la vida.' : ' (mine-mill, mill-market, mine-market): the cut-off at which two stages saturate simultaneously, equalising their throughput times over the life.'}</p>
              <p>{es ? 'La intuición de cada forma: cuando la mina limita, el tiempo de molino es gratis, así que el corte cae al break-even (procesar lo que pague su propio proceso). Cuando el molino limita, procesar un bloque ocupa una hora de molino que vale τ/H, así que el bloque debe pagar ese "alquiler" además de su costo, de ahí el término +τ/H que eleva el corte. Cuando el mercado limita, lo escaso es el metal vendible, no la roca, así que la penalización entra en el margen como −τ/K. Cada forma es el mismo principio, cobrar al bloque marginal el costo de oportunidad de la capacidad que consume, aplicado a la etapa que escasea.' : 'The intuition behind each form: when the mine binds, mill time is free, so the cut-off falls to break-even (process what pays its own processing). When the mill binds, processing a block occupies an hour of mill time worth τ/H, so the block must pay that "rent" on top of its cost, hence the +τ/H term that raises the cut-off. When the market binds, the scarce thing is sellable metal, not rock, so the penalty enters the margin as −τ/K. Each form is the same principle, charge the marginal block the opportunity cost of the capacity it consumes, applied to whichever stage is scarce.'}</p>
              <p>{es ? 'Cuál de los seis aplica depende del depósito y la economía: a precio alto con molino chico domina el régimen molino-limitado (cortes altos, high-grading fuerte); a precio bajo o mina chica domina mina-limitado (corte cerca del break-even). El régimen puede incluso cambiar a lo largo de la vida a medida que F decae. La regla mediana de Dagdelen elige automáticamente el corte efectivo, y la pestaña "Utilización de capacidad" del App muestra, año a año, qué etapa se satura.' : 'Which of the six applies depends on the deposit and the economics: at high price with a small mill the mill-limited regime dominates (high cut-offs, strong high-grading); at low price or a small mine the mine-limited regime dominates (cut-off near break-even). The regime can even switch over the life as F decays. Dagdelen\'s median rule automatically picks the effective cut-off, and the App\'s "Capacity utilisation" tab shows, year by year, which stage saturates.'}</p>
              <Equation tex="\hat g=\operatorname{median-rule}\big(g_{\text{mina}},g_{\text{molino}},g_{\text{mercado}},g_{mh},g_{hk},g_{mk}\big)" caption={es ? 'la construcción mediana de Dagdelen selecciona el corte efectivo entre los seis (la lógica "qué etapa limita")' : 'Dagdelen median construction selects the effective cut-off among the six (the "which stage binds" logic)'} />
              <Callout variant="note" title={es ? 'Por qué el corte decrece' : 'Why the cut-off declines'}>
                {es ? 'Cuando el molino o el mercado limitan, ocupar esa capacidad un año cuesta ' : 'When the mill or the market binds, occupying that capacity for a year costs '}<InlineMath tex="\tau=f+F\delta" />{es ? ', así que el corte sube sobre el break-even. Al agotarse la reserva, ' : ', so the cut-off rises above break-even. As the reserve depletes, '}<InlineMath tex="F\to0" />{es ? ', ' : ', '}<InlineMath tex="\tau\to f" />{es ? ' y el corte cae al break-even. Eso es el high-grading ' : ' and the cut-off falls to break-even. That is high-grading '}<Cite id="lane1988" paren />{es ? '. La pestaña "Costo de oportunidad τ(t)" del App lo muestra en vivo.' : '. The App\'s "Opportunity cost τ(t)" tab shows it live.'}
              </Callout>
              <figure className="cg-fig">
                <svg viewBox="0 0 460 150" width="100%" role="img" className="cg-msvg" aria-label={es ? 'los seis cortes de Lane sobre un eje de ley' : 'the six Lane cut-offs on a grade axis'}>
                  <line className="ax" x1="30" y1="100" x2="440" y2="100" /><text className="s" x="380" y="120">{es ? 'ley →' : 'grade →'}</text>
                  {[[90, 'g_mina', 'la'], [150, 'g_mk', 'fl'], [210, 'g_molino', 'gd'], [270, 'g_mh', 'fl'], [330, 'g_hk', 'fl'], [390, 'g_mercado', 'la']].map(([x, lbl, cls], i) => (
                    <g key={i}><line className={cls as string} x1={x as number} y1="60" x2={x as number} y2="100" style={i === 2 ? { strokeWidth: 3 } : {}} /><text className="s" x={(x as number) - 16} y="52">{lbl as string}</text></g>
                  ))}
                  <text className="s" x="186" y="132">{es ? 'el binding (resaltado) es el corte efectivo' : 'the binding one (bold) is the effective cut-off'}</text>
                </svg>
                <figcaption>{es ? 'Los 6 cortes en un eje de ley: 3 limitantes + 3 balanceadores; la regla mediana de Dagdelen elige el efectivo.' : 'The 6 cut-offs on a grade axis: 3 limiting + 3 balancing; Dagdelen\'s median rule picks the effective one.'}</figcaption>
              </figure>
              <Refs ids={['lane1988', 'dagdelen1992']} label="Refs" />
            </div>
          ),
        },
        // ============================================================ NPV OPTIMIZATION
        {
          id: 'npv', label: es ? 'Optimización VAN' : 'NPV optimization',
          content: (
            <div className="cg-doc-sec">
              <p>{es ? 'Como ' : 'Because '}<InlineMath tex="F" />{es ? ' aparece en el corte y el corte determina los flujos que determinan ' : ' appears in the cut-off and the cut-off determines the cashflows that determine '}<InlineMath tex="F" />{es ? ', el óptimo es un ' : ', the optimum is a '}<b>{es ? 'punto fijo' : 'fixed point'}</b>{es ? ' resuelto sobre la vida. Un simulador exacto año a año da el VAN de cualquier política de corte:' : ' solved over the life. An exact year-by-year simulator gives the NPV of any cut-off policy:'}</p>
              <Equation tex="\text{VAN}=\sum_{t}\frac{C_t}{(1+\delta)^t},\qquad C_t=\text{ore}_t\,\bar g_t\,y(p-k)-\text{ore}_t\,h-Q_t\,m-f" caption={es ? 'VAN como suma de flujos descontados; C_t = ingreso − costo de proceso − costo de minería (Q_t·m) − costo fijo f' : 'NPV as the sum of discounted cashflows; C_t = revenue − processing cost − mining cost (Q_t·m) − fixed cost f'} />
              <p>{es ? 'El throughput de cada año está limitado por la etapa que satura: ' : 'Each year\'s throughput is limited by the saturating stage: '}<InlineMath tex="Q_t=\min(M,\,H/\phi,\,K/(\phi\bar g y),\,R)" />{es ? '. La iteración de punto fijo se siembra con el calendario del mejor corte constante, calcula el calendario de Lane desde su perfil F hacia atrás, recalcula F desde los nuevos flujos, y repite.' : '. The fixed-point iteration is seeded with the best-constant schedule, computes the Lane schedule from its backward F-profile, recomputes F from the new cashflows, and repeats.'}</p>
              <Equation tex="g^{(n+1)}=\text{Lane}\big(\tau^{(n)}\big),\quad \tau^{(n)}=f+F\big(g^{(n)}\big)\,\delta,\qquad \frac{\big|\text{NPV}^{(n+1)}-\text{NPV}^{(n)}_{\text{best}}\big|}{\max\big(1,\ \big|\text{NPV}^{(n)}_{\text{best}}\big|\big)}<10^{-6}" caption={es ? 'la recurrencia de punto fijo: el corte y τ se refinan mutuamente; la regla de parada implementada es el cambio relativo de VAN bajo 1e-6 (máximo 40 iteraciones)' : 'the fixed-point recurrence: the cut-off and τ refine each other; the implemented stopping rule is the relative NPV change below 1e-6 (at most 40 iterations)'} />
              <p>{es ? 'El óptimo constante (búsqueda 1-D refinada por golden-section) es la línea base verificable; la política decreciente de Lane (la iteración) es ' : 'The optimal constant cut-off (a 1-D search refined by golden-section) is the verifiable baseline; the declining Lane policy (the iteration) is '}<InlineMath tex="\geq" />{es ? ' el mejor constante ' : ' the best constant '}<Cite id="asad2011" paren />{es ? '. El App reporta el uplift exacto entre ambos.' : '. The App reports the exact uplift between them.'}</p>
              <p>{es ? 'La convergencia del punto fijo no es gratuita: para decks patológicos la iteración puede oscilar en vez de asentarse. Las guardas implementadas son simples y declaradas: el motor limita las iteraciones a 40, se queda con el mejor calendario por VAN visto en cualquier iteración (así una corrida oscilante devuelve su mejor iterada, nunca peor que la semilla del óptimo constante), y se detiene cuando el cambio relativo de VAN cae bajo 1e-6. El motor no amortigua la actualización y todavía no expone una traza de convergencia por iteración ni una bandera de no-convergencia, eso está en el roadmap, no en el motor.' : 'The fixed-point\'s convergence is not free: for pathological decks the iteration can oscillate rather than settle. The implemented guards are simple and disclosed: the engine caps the iterations at 40, keeps the best-NPV schedule seen at any iteration (so an oscillating run returns its best iterate, never worse than the constant-optimum seed), and stops when the relative NPV change falls below 1e-6. The engine does not damp the update and does not yet expose a per-iteration convergence trace or a non-convergence flag, that is roadmap, not in the engine.'}</p>
              <figure className="cg-fig">
                <svg viewBox="0 0 460 170" width="100%" role="img" className="cg-msvg" aria-label={es ? 'el lazo de punto fijo VAN ↔ corte' : 'the NPV ↔ cut-off fixed-point loop'}>
                  {[[40, 'corte g', 'cut-off g', 'hi'], [180, 'calendario', 'schedule', 'bx'], [320, 'VAN + F', 'NPV + F', 'gd']].map(([x, esl, enl, cls], i) => (
                    <g key={i}><rect className={`bx ${cls}` as string} x={x as number} y="50" width="100" height="48" rx="8" /><text className="t" x={(x as number) + 50} y="72" textAnchor="middle">{es ? esl as string : enl as string}</text></g>
                  ))}
                  <path className="fl" d="M140,74 H178" markerEnd="url(#cg-ma)" /><path className="fl" d="M280,74 H318" markerEnd="url(#cg-ma)" />
                  <path className="fl" d="M370,98 C370,140 90,140 90,100" markerEnd="url(#cg-ma)" /><text className="s" x="170" y="135">τ = f + F·δ {es ? 'reabre el corte' : 're-opens the cut-off'}</text>
                  <defs><marker id="cg-ma" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L8,4 L0,8 z" fill="var(--color-fg-faint)" /></marker></defs>
                  <text className="s" x="36" y="40">{es ? 'siembra: el óptimo constante → itera (máx 40)' : 'seed: the constant optimum → iterate (max 40)'}</text>
                </svg>
                <figcaption>{es ? 'El lazo de punto fijo: corte → calendario → VAN+F → τ → corte, hasta que el cambio relativo de VAN cae bajo 1e-6.' : 'The fixed-point loop: cut-off → schedule → NPV+F → τ → cut-off, until the relative NPV change falls below 1e-6.'}</figcaption>
              </figure>
              <Callout variant="honest" title={es ? 'Convenciones operativas (divergen de Lane de libro)' : 'Operating conventions (diverge from textbook Lane)'}>
                {es ? 'Dos convenciones explícitas en el motor: (1) la mina cierra el primer año en que el flujo de caja se vuelve ≤ 0, Lane estricto opera hasta agotar la reserva con F→0, así que esto acorta la vida reportada y nunca reporta años de valor negativo; (2) el corte se acota a [break-even, ley máxima], Lane estricto permite cortes bajo break-even en los últimos años (material marginal → stockpile/blend), así que el clamp sube levemente el VAN reportado. Ambas son decisiones de operación, no Lane estricto.' : 'Two explicit conventions in the engine: (1) the mine closes the first year cashflow turns ≤ 0, strict Lane runs to reserve exhaustion at F→0, so this shortens reported life and never reports value-negative years; (2) the cut-off is clamped to [break-even, max grade], strict Lane allows sub-break-even cut-offs in the final years (marginal material → stockpile/blend), so the clamp slightly raises reported NPV. Both are operating decisions, not strict Lane.'}
              </Callout>
              <Refs ids={['asad2011', 'lane1988']} label="Refs" />
            </div>
          ),
        },
        // ============================================================ STOCHASTIC
        {
          id: 'stochastic', label: es ? 'Estocástico (roadmap)' : 'Stochastic (roadmap)',
          content: (
            <div className="cg-doc-sec">
              <Callout variant="strong" title={es ? 'Roadmap, no implementado en el producto' : 'Roadmap, not implemented in the product'}>
                {es ? 'Esta pestaña documenta el diseño del tier estocástico. Hoy no se computa ningún Monte-Carlo en ninguna parte del producto: ni en el App (la pestaña What-if hace una inferencia del surrogate por cambio de control), ni en el pipeline. No existen distribuciones ni percentiles de VAN calculados. Las ecuaciones y la figura de abajo son el método objetivo, no un resultado.' : 'This tab documents the design of the stochastic tier. Today no Monte-Carlo is computed anywhere in the product: not in the App (the What-if tab performs one surrogate inference per control change), not in the pipeline. No NPV distributions or percentiles exist as computed results. The equations and figure below are the target method, not a result.'}
              </Callout>
              <p>{es ? 'La política óptima de Lane es determinista: asume precio y costos fijos. Pero el precio del metal es la mayor incertidumbre de cualquier proyecto minero. La extensión estocástica trata el precio (y los costos) como variables aleatorias y propaga su distribución al VAN.' : 'The Lane optimal policy is deterministic: it assumes fixed price and costs. But metal price is the single biggest uncertainty in any mining project. The stochastic extension treats price (and costs) as random variables and propagates their distribution to the NPV.'}</p>
              <Equation tex="\text{VAN}^{(s)}=\text{Lane}\big(p^{(s)},\,k^{(s)},\,\dots\big),\qquad p^{(s)}\sim\mathcal{D}_{\text{precio}},\ \ s=1\ldots S" caption={es ? 'Monte-Carlo: S muestras de los inputs inciertos → S valores de VAN, cada uno del optimizador de Lane (o su surrogate)' : 'Monte-Carlo: S samples of the uncertain inputs → S NPV values, each from the Lane optimizer (or its surrogate)'} />
              <p>{es ? 'El resultado no es un número sino una distribución de VAN, resumida por sus percentiles y por la probabilidad de que el proyecto sea positivo:' : 'The result is not a number but a distribution of NPV, summarised by its percentiles and the probability the project is positive:'}</p>
              <Equation tex="\text{P10}=Q_{0.1},\ \text{P50}=Q_{0.5},\ \text{P90}=Q_{0.9},\qquad \Pr(\text{VAN}>0)=\tfrac{1}{S}\textstyle\sum_s \mathbb{1}\!\left[\text{VAN}^{(s)}>0\right]" caption={es ? 'percentiles P10/P50/P90 de la distribución de VAN y la probabilidad de un proyecto con valor positivo' : 'P10/P50/P90 percentiles of the NPV distribution and the probability of a value-positive project'} />
              <p>{es ? 'Aquí es donde el surrogate aprendido ganaría su lugar: el optimizador exacto es barato para un caso, pero un Monte-Carlo de 10⁴+ corridas se vuelve pesado en vivo. El surrogate ONNX ya entrenado evalúa una muestra en microsegundos, así que la distribución de VAN podría calcularse interactivamente cuando este tier se implemente, ese es el rol planificado del surrogate. Modelos de precio con reversión a la media (Ornstein-Uhlenbeck) o GBM enriquecerían ' : 'This is where the learned surrogate would earn its place: the exact optimizer is cheap for one case, but a 10⁴+ run Monte-Carlo gets heavy live. The already-trained ONNX surrogate evaluates a sample in microseconds, so the NPV distribution could be computed interactively once this tier ships, that is the surrogate\'s planned role. Mean-reverting (Ornstein-Uhlenbeck) or GBM price models would enrich '}<InlineMath tex="\mathcal{D}_{\text{precio}}" />{es ? '.' : '.'}</p>
              <p>{es ? 'El valor de decisión está en los percentiles, no en la media: un proyecto con P50 positivo pero P10 muy negativo es frágil al precio y exige cobertura o un corte más conservador; uno con P10 sobre cero es robusto. La extensión de opciones reales va más allá, el derecho a high-gradear o a stockpilear material marginal cuando el precio cae tiene valor por sí mismo, pero el tier planificado se detiene deliberadamente en el Monte-Carlo honesto: propagar la incertidumbre del precio, no pretender modelar la flexibilidad operacional completa que ningún optimizador estático captura.' : 'The decision value is in the percentiles, not the mean: a project with a positive P50 but a deeply negative P10 is price-fragile and demands hedging or a more conservative cut-off; one with P10 above zero is robust. The real-options extension goes further, the right to high-grade or to stockpile marginal material when the price falls has value in itself, but the planned tier deliberately stops at honest Monte-Carlo: propagate price uncertainty, not pretend to model the full operational flexibility no static optimizer captures.'}</p>
              <figure className="cg-fig">
                <svg viewBox="0 0 460 200" width="100%" role="img" className="cg-msvg" aria-label={es ? 'distribución de VAN Monte-Carlo objetivo con P10/P50/P90 (ilustrativa, roadmap)' : 'target Monte-Carlo NPV distribution with P10/P50/P90 (illustrative, roadmap)'}>
                  <line className="ax" x1="44" y1="170" x2="440" y2="170" />
                  <path className="fan" d="M60,170 C140,150 180,60 240,52 C300,60 340,150 420,170 Z" />
                  <path className="la" d="M60,170 C140,150 180,60 240,52 C300,60 340,150 420,170" />
                  <line className="lw" x1="150" y1="40" x2="150" y2="170" /><text className="s" x="134" y="32">P10</text>
                  <line className="gd" x1="240" y1="30" x2="240" y2="170" style={{ strokeWidth: 1.2, strokeDasharray: '3 3' }} /><text className="s" x="228" y="24">P50</text>
                  <line className="lw" x1="330" y1="40" x2="330" y2="170" /><text className="s" x="314" y="32">P90</text>
                  <text className="s" x="200" y="190">VAN →</text><text className="s" x="60" y="150">{es ? 'Pr(VAN>0)' : 'Pr(NPV>0)'}</text>
                </svg>
                <figcaption>{es ? 'La salida objetivo del tier estocástico (figura ilustrativa, no computada en el producto hoy): P10/P50/P90 y la probabilidad de valor positivo.' : 'The stochastic tier\'s target output (illustrative figure, not computed in the product today): P10/P50/P90 and the probability of positive value.'}</figcaption>
              </figure>
              <Callout variant="honest" title={es ? 'Honestidad de la incertidumbre' : 'Uncertainty honesty'}>
                {es ? 'La distribución de precio es un modelo, no una predicción. Y esta pestaña completa es un diseño: nada estocástico está computado en el producto hoy. Cuando el tier llegue, su valor estará en propagar la incertidumbre honestamente (un intervalo, no un punto), no en afirmar conocer el precio futuro del cobre.' : 'The price distribution is a model, not a prediction. And this whole tab is a design: nothing stochastic is computed in the product today. When the tier lands, its value will be in propagating uncertainty honestly (an interval, not a point), not in claiming to know the future copper price.'}
              </Callout>
              <Refs ids={['asad2011', 'hall2014']} label="Refs" />
            </div>
          ),
        },
        // ============================================================ LEARNED
        {
          id: 'learned', label: es ? 'Aprendido' : 'Learned',
          content: (
            <div className="cg-doc-sec">
              <p>{es ? 'Dos modelos aprendidos, honestos, medidos contra el optimizador exacto. (1) Un ' : 'Two honest learned models, measured against the exact optimizer. (1) An '}<b>{es ? 'surrogate MLP' : 'MLP surrogate'}</b>{es ? ': un perceptrón multicapa que mapea las features del depósito + economía al corte óptimo, el VAN y la vida, un sustituto en microsegundos del optimizador, comparado en vivo contra él en la pestaña What-if (los barridos Monte-Carlo masivos son el tier estocástico del roadmap).' : ': a multilayer perceptron mapping the deposit + economic features to the optimal cut-off, NPV and life, a microsecond stand-in for the optimizer, compared live against it in the What-if tab (mass Monte-Carlo sweeps are the roadmap stochastic tier).'}</p>
              <Equation tex="\hat y=\text{MLP}_\theta(x),\qquad \theta^\*=\arg\min_\theta \tfrac{1}{N}\textstyle\sum_i \big\|\text{MLP}_\theta(x_i)-y_i^{\text{exacto}}\big\|^2" caption={es ? 'el surrogate se entrena para reproducir la salida del optimizador exacto (x = features depósito+economía; y = corte/VAN/vida)' : 'the surrogate is trained to reproduce the exact optimizer output (x = deposit+economic features; y = cut-off/NPV/life)'} />
              <p>{es ? '(2) Un ' : '(2) A '}<b>{es ? 'autoencoder de escenarios' : 'scenario autoencoder'}</b>{es ? ' que aprende a reconstruir los escenarios de entrenamiento; un punto con error de reconstrucción alto está fuera del envolvente de entrenamiento, el surrogate está extrapolando y no se debe confiar en él ahí.' : ' that learns to reconstruct the training scenarios; a point with high reconstruction error is outside the training envelope, the surrogate is extrapolating and must not be trusted there.'}</p>
              <Equation tex="\text{OOD}(x)=\big\|x-\text{AE}(x)\big\|^2,\qquad \text{marca si } \text{OOD}(x)>\theta_{p95}" caption={es ? 'el puntaje fuera-de-distribución es el error de reconstrucción del AE; se marca sobre el umbral p95 in-distribución del entrenamiento' : 'the out-of-distribution score is the AE reconstruction error; flagged above the training in-distribution p95 threshold'} />
              <p>{es ? 'Ambos se entrenan offline (torch → ONNX) y se ejecutan en vivo en el navegador (onnxruntime-web). Sus métricas held-out se reportan tal cual: el surrogate tiene ~6.8% de error de VAN y ~10.9% de error de corte; el OOD-AE separa dentro/fuera con AUC 0.999. Nada de victorias fabricadas, el optimizador exacto es la autoridad, y el surrogate solo gana su lugar donde la velocidad importa.' : 'Both train offline (torch → ONNX) and run live in the browser (onnxruntime-web). Their held-out metrics are reported as they land: the surrogate has ~6.8% NPV error and ~10.9% cut-off error; the OOD-AE separates in/out at AUC 0.999. No fabricated wins, the exact optimizer is the authority, and the surrogate only earns its place where speed matters.'}</p>
              <p>{es ? 'El protocolo es honesto por construcción: ambos modelos se entrenan sobre un muestreo del espacio de depósitos + economía, se evalúan en un conjunto retenido que no se vio en entrenamiento, y las métricas se reportan sobre ese held-out (no sobre los datos de entrenamiento, donde cualquier modelo parece perfecto). El vector de features son cantidades ya interpretables, media y variabilidad de ley, precio, costos, capacidades, descuento, no píxeles crudos, así que las salidas del surrogate se pueden auditar contra la intuición económica.' : 'The protocol is honest by construction: both models train on a sampling of the deposit + economic space, are evaluated on a held-out set unseen in training, and the metrics are reported on that held-out set (not on the training data, where any model looks perfect). The feature vector is already-interpretable quantities, grade mean and variability, price, costs, capacities, discount, not raw pixels, so the surrogate\'s outputs can be audited against economic intuition.'}</p>
              <figure className="cg-fig">
                <svg viewBox="0 0 460 160" width="100%" role="img" className="cg-msvg" aria-label={es ? 'pipeline de los modelos aprendidos' : 'learned-models pipeline'}>
                  {[[20, 'optimizador exacto', 'exact optimizer', 'gd'], [150, 'muestras (x, y)', 'samples (x, y)', 'bx'], [280, 'MLP + AE → ONNX', 'MLP + AE → ONNX', 'hi']].map(([x, esl, enl, cls], i) => (
                    <g key={i}><rect className={`bx ${cls}` as string} x={x as number} y="40" width="116" height="46" rx="8" /><text className="t" x={(x as number) + 58} y="60" textAnchor="middle" style={{ fontSize: 10 }}>{es ? esl as string : enl as string}</text></g>
                  ))}
                  <rect className="bx hi" x="280" y="104" width="160" height="40" rx="8" /><text className="t" x="360" y="128" textAnchor="middle" style={{ fontSize: 10 }}>{es ? 'vivo en navegador' : 'live in browser'}</text>
                  <path className="fl" d="M136,63 H148" markerEnd="url(#cg-mb)" /><path className="fl" d="M266,63 H278" markerEnd="url(#cg-mb)" /><path className="fl" d="M360,86 V102" markerEnd="url(#cg-mb)" />
                  <defs><marker id="cg-mb" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L8,4 L0,8 z" fill="var(--color-fg-faint)" /></marker></defs>
                  <text className="s" x="20" y="110">{es ? 'surrogate: err VAN ~6.8% · OOD-AE: AUC 0.999' : 'surrogate: NPV err ~6.8% · OOD-AE: AUC 0.999'}</text>
                </svg>
                <figcaption>{es ? 'El exacto genera los datos; el MLP + AE se entrenan, exportan a ONNX y se ejecutan en vivo, medidos contra el exacto.' : 'The exact engine generates the data; the MLP + AE train, export to ONNX and run live, measured against the exact.'}</figcaption>
              </figure>
              <Callout variant="honest" title={es ? 'El exacto es la autoridad' : 'The exact engine is the authority'}>
                {es ? 'El surrogate no reemplaza al optimizador: el exacto se ejecuta en vivo por defecto y es la referencia. El surrogate está construido para los barridos masivos donde 10⁴ corridas exactas serían lentas (el tier Monte-Carlo del roadmap); hoy el App lo usa para la comparación de un escenario a la vez en What-if, y siempre se reporta su error contra el exacto. El OOD-AE evita que se use ciegamente fuera de su envolvente.' : 'The surrogate does not replace the optimizer: the exact engine runs live by default and is the reference. The surrogate is built for the mass sweeps where 10⁴ exact runs would be slow (the roadmap Monte-Carlo tier); today the App uses it for the one-scenario-at-a-time What-if comparison, and its error against the exact is always reported. The OOD-AE keeps it from being used blindly outside its envelope.'}
              </Callout>
              <Refs ids={['hall2014', 'rendu2014']} label="Refs" />
            </div>
          ),
        },
      ]} />
    </article>
  );
}
